SQL課題2の提出
kaneyan0607/quelcode-db pull request #2
Opened 2020-06-17 06:49 UTC by kaneyan0607

# やったこと

- 課題①で作成したER図を基に、物理設計とDDL文を作成

2020-06-17 07:37 UTC, piasoratech requested changes
テーブル定義書指摘事項
- `users`テーブルの定義で要件を満たしていない項目があります。
- フラグ系の命名は`is_xxxx`とするのが一般的です。
- デフォルト値の書き方が違います。記入例を参考にしてください。
- 全体的に作成者idの物理名の時系列が違うので確認してください。
- 一部の項目で`text`型を採用していますが、`text`型は文字数管理ではなくbyte数管理なのでこの定義では要件を満たせていないのがほとんどです。基本的には`varchar`での管理で良いです。違いについては[こちらのページ](http://lxyuma.hatenablog.com/entry/2015/08/15/131309)を参考にしてみてください。
- `chat_room_entries`テーブルが今の構造だと同じユーザーが同じチャットルームに重複して参加することを許容してしまうので、もう少し考えてみましょう。
- `chat_room_entries`テーブルのユーザー参加日時の物理名の時系列を確認してください。

今回の指摘内容を踏まえて定義書の更新とDDL文の修正・確認をお願いします！

2020-06-17 16:47 UTC, kaneyan0607 commented
# やったこと
- usersテーブルにてself_introduction（自己紹介文）カラムの定義を誤っていたため長さを(1000)に修正
- フラグ系の命名をis_xxxxに修正
- データベース定義書のデフォルト値の書き方を誤っていたため記入例と同じように修正
- 各テーブルの作成者idとchat_room_entriesテーブルのユーザー参加日時の物理名の時系列が誤っていた命名の規則性を統一
- データベース定義書にて、一部の項目でtext型を定義しており、varchar型にしていなかったため、varchar型に修正。(init.sqlではtext型を記述していないため、varchar型のままです。エクセルシートで作業中、text型ではなくvarchar型が適正だと気づいたものの、varchar型に置換するのを忘れ、そのまま記述したまま提出してしまいました。)
- chat_room_entriesテーブルにて、同じユーザーが同じチャットルームに重複して参加することを許容していたので、構造を修正。`chat_room_entry_id`カラムを削除し`user_id`,`chat_room_id`
カラムをプライマリキーとして複数指定し、問題を解決しました。

2020-06-18 02:53 UTC, piasoratech requested changes
だいぶ良くなりました！が、1点だけ指摘します。
- `tasks`テーブルの`is_complete`は`is_deleted`などと同じように動詞部分を過去形にしておきましょう。なぜ過去にするかというと日本語で状態を考えた時に削除した、完了したといったように○○したという過去の表現をすることがほとんどだからです。

2020-06-18 03:30 UTC, kaneyan0607 commented
# やったこと
- tasksテーブルのis_completeカラムの命名を過去形に修正
(日本語で状態を考えた時に削除した、完了したといったように○○したという過去の表現をする為）

2020-06-18 03:34 UTC, piasoratech approved these changes
OKです！
次に進みましょう！

2020-06-18 03:43 UTC, merged