DB課題3 / 1回目の提出
kaneyan0607/quelcode-db pull request #5
Opened 2020-06-19 03:53 UTC by kaneyan0607

# やったこと
### 編集中のDB課題3を一旦マージさせてDB課題2編集用に新しくブランチをきり、DB課題2をマージさせました。（DB課題2の修正箇所が見つかった為）その為、DB課題3を新しいブランチで切りました。
- 課題1~5の内容を実行。
- 実行後の画面キャプチャを格納

2020-06-19 05:00 UTC, piasoratech requested changes
提出するものは以下のものになるので、確認して再提出してください。
- 実行後のキャプチャ
- 実行したSQL文(.sqlで格納)

2020-06-19 05:34 UTC, kaneyan0607 commented
# やったこと
DB課題3をマージしてしまい、このブランチで.sqlのコミット履歴ないため、改行で差分を追加しコミット。

2020-06-19 07:28 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-19 07:28 UTC, piasoratech commented on db/db-challenge3/db-003/db_003.sql
> +
実行結果には影響ないですが、`chat_room_id`の空白がそろってないのは違和感を感じるので修正してください

2020-06-19 07:28 UTC, piasoratech commented on db/db-challenge3/db-004/db_004.sql
> +
こちらもNo003と同じ指摘です。

2020-06-19 07:28 UTC, piasoratech commented on db/db-challenge3/db-005/db_005.sql
> +
こちらもNo003,004と同様の指摘です

2020-06-19 07:52 UTC, kaneyan0607 commented
# やったこと
- db_003.sql, db_004.sql, db_005.sql の空白が全角や不自然なスペースが挿入されており、並びも揃っていなかった為、半角スペースで統一し、空白を揃えました。

2020-06-19 08:22 UTC, piasoratech reviewed
No001～005は確認OKです
次に進みましょう！

2020-06-22 06:57 UTC, kaneyan0607 commented
# やったこと
add:問題番号007の実行画面スクリーンショット 37e3baa
↑こちらのコミット名に誤りがあります。正しくは「問題番号006の実行画面スクリーンショット」です。よろしくお願いします。
- 課題6~10の内容を実行。
- 実行後の画面キャプチャを格納

2020-06-22 08:41 UTC, himaru-jp requested changes

2020-06-22 08:41 UTC, himaru-jp commented on db/db-challenge3/db-008/db_008.sql
> +SELECT users.name, chat_rooms.chat_room_name, CAST(chat_room_entries.participated_at AS DATE)
　・削除されているユーザー、削除されているチャットルームは表示しないこと
という要件を満たしていません。ご確認をお願いします。

2020-06-22 08:41 UTC, himaru-jp commented on db/db-challenge3/db-010/db_010.sql
> +AND posts.created_at IN(
削除されているユーザの投稿を含まずに最新の投稿を取得するようにしてください。
また、チャットの数が膨大になると投稿日時がかぶる場合もあるので、投稿日時のみを抽出条件とせず、chat_room_idもINの条件に含めると良いです。

2020-06-22 08:41 UTC, himaru-jp commented on db/db-challenge3/db-009/db_009.sql
> +AND posts.created_user_id IN (
要件としては正しく動作していますが、削除されているユーザをサブクエリで絞りこんでいるのには理由がありますか？

2020-06-22 15:50 UTC, kaneyan0607 commented
# やったこと
- 問題番号8　削除されているユーザー、削除されているチャットルームは表示するよう修正。
- 問題番号9　コメントに回答しました。
- 問題番号10 削除されているユーザの投稿を含まずに最新の投稿を取得するよう修正。
　　　　　また、投稿日時のみを抽出条件とせず、chat_room_idもINの条件に含めました。

2020-06-22 15:51 UTC, kaneyan0607 commented on db/db-challenge3/db-009/db_009.sql
> +AND posts.created_user_id IN (
投稿をしたユーザーidがユーザーテーブルの削除されていないユーザーのユーザーidと一致した場合を対象に絞るようサブクエリで記述致しました🙇‍♂️（users.is_deleted = 0）

2020-06-23 04:42 UTC, fjtawork reviewed
まだ途中なので、ちょっと待ってくださいね。
修正するかどうかはお任せしますが、知識として覚えておくといいことをコメントしました。

2020-06-23 04:42 UTC, fjtawork commented on db/db-challenge3/db-009/db_009.sql
> +AND posts.created_user_id IN (
要件通りに動くようなのでOKなのですが、この場合はjoinを使って絞るのが一般的ですね。
理由はそのほうがDBの動作が早い場合が多いからです。

基本はjoinを使って絞り込む。
joinだと狙ったデータが取れない場合、サブクエリのほうが早く動く場合にはサブクエリを使う、みたいな感覚かなと。

2020-06-23 07:15 UTC, fjtawork commented
お待たせしました！
010.sqlが僕があまり使ったこと無いSQLなので他の講師に確認してて遅くなりました。

内容OKです。次に進みましょう！

2020-06-23 07:24 UTC, kaneyan0607 commented
# やったこと　DB課題3 / 2 の修正
- 問題番号009 joinを使って絞るように修正いたしました
　　　　　　　理由：DBの動作が早い場合が多い為。
（スクリーンショットの画像を差し替えました。）

2020-06-23 08:17 UTC, fjtawork commented
OKです！LGTM!

2020-06-23 08:21 UTC, kaneyan0607 commented
# やったこと DB課題3 / 3 の提出
- 課題11~14の内容を実行。
- 実行後の画面キャプチャを格納

2020-06-23 09:30 UTC, fjtawork reviewed
気になった２点、コメントしました

2020-06-23 09:30 UTC, fjtawork commented on db/db-challenge3/db-012/db_012.sql
> +SET chat_rooms.is_suppression = 0, chat_rooms.updated_user_id = 1, chat_rooms.updated_at = NOW()
気になったのでコメント入れます。

SET句のところでchat_rooms.is_suppressionのようにテーブル名(chat_rooms）を付けてますが、これの意図は何でしょう？
なくても動くと思うのですが。

2020-06-23 09:30 UTC, fjtawork commented on db/db-challenge3/db-012/db_012.sql
> +    WHERE chat_room_entries.user_id = 1 )
動作的には問題でなそうなのですが、コメントします。

このサブクエリですがchat_room_entries.chat_room_idは、同じ結果が複数レコード、出てくる可能性がありますよね。
なので `DISTINCT`とかにしてあげると、より良い。という感じかなと。

2020-06-23 13:13 UTC, kaneyan0607 commented on db/db-challenge3/db-012/db_012.sql
> +SET chat_rooms.is_suppression = 0, chat_rooms.updated_user_id = 1, chat_rooms.updated_at = NOW()
すみません特に意図はございません！記述していく中で自分の頭の中を整理しやすいよう記述した限りで無くても動作すにもかかわらず削除し忘れておりました。🙇‍♂️

2020-06-23 16:35 UTC, kaneyan0607 commented
# やったこと DB課題3 / 3 の修正
※SQL文を書き直した問題はスクショを差し替えています。
- 問題番号11　不要なテーブル名の記述を削除。セミコロンを追記
- 問題番号12　SET句のところで不要なテーブル名の記述を削除。サブクエリにてDISTINCT句を追記
- 問題番号13　SET句のところで不要なテーブル名の記述を削除。

2020-06-24 02:52 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-06-24 05:21 UTC, merged